# -*- coding: utf-8 -*-
"""ec24158_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEf9gujHXp-QDImsPaUavnkG_a93O8N1
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

class MyCNN(nn.Module):
    def __init__(self):
        super(MyCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=5, stride=1, padding=0)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, stride=1, padding=0)
        self.fc1 = nn.Linear(64 * 4 * 4, 1024)
        self.fc2 = nn.Linear(1024, 256)
        self.fc3 = nn.Linear(256, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.pool(x)
        x = self.relu(self.conv2(x))
        x = self.pool(x)
        x = x.view(-1, 64 * 4 * 4)  # Flatten the output
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

def train_and_evaluate():
    train_set = torchvision.datasets.FashionMNIST(root = ".", train=True,
                                              download=True,
                                              transform=transforms.ToTensor())
    validation_set = torchvision.datasets.FashionMNIST(root = ".", train=False,
                                             download=True,
                                             transform=transforms.ToTensor())
    train_loader = torch.utils.data.DataLoader(train_set, batch_size=32, shuffle=True)
    validation_loader = torch.utils.data.DataLoader(validation_set, batch_size=32, shuffle=False)

    for images, labels in train_loader:
      print(f"Image batch shape: {images.shape}")
      print(f"Label batch shape: {labels.shape}")

    model = MyCNN()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.1)
    torch.manual_seed(0)
    num_epochs = 30

    train_acc = []
    val_acc = []
    train_loss = []
    val_loss = []

    # Training loop
    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        train_acc.append(100 * correct / total)
        train_loss.append(running_loss / len(train_loader))

        # Validation loop
        model.eval()
        val_running_loss = 0.0
        val_correct = 0
        val_total = 0
        with torch.no_grad():
            for images, labels in validation_loader:
                outputs = model(images)
                loss = criterion(outputs, labels)
                val_running_loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        val_acc.append(100 * val_correct / val_total)
        val_loss.append(val_running_loss / len(validation_loader))

        print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss[-1]:.4f}, Train Acc: {train_acc[-1]:.2f}%, "
              f"Val Loss: {val_loss[-1]:.4f}, Val Acc: {val_acc[-1]:.2f}%")

    # Save the model
    torch.save(model.state_dict(), "best_cnn.pth")

    return train_acc, val_acc, train_loss, val_loss
train_and_evaluate()

import matplotlib.pyplot as plt

train_acc = [77.245, 87.523, 89.485, 90.597, 91.557, 92.278, 92.942, 93.585, 94.22, 94.718,
             95.133, 95.588, 96.005, 96.558, 96.605, 96.813, 97.323, 97.327, 97.7, 97.875,
             97.94, 98.217, 98.258, 98.385, 98.578, 98.722, 98.835, 99.032, 98.955, 98.858]
val_acc = [85.0, 87.68, 88.84, 89.88, 89.72, 90.11, 90.07, 89.85, 90.14, 90.9,
           90.79, 91.16, 90.69, 91.25, 90.85, 91.22, 91.19, 90.28, 90.8, 91.3,
           91.22, 91.32, 90.87, 91.22, 90.9, 90.67, 91.18, 91.34, 90.99, 91.18]
train_loss = [0.6083, 0.3413, 0.2857, 0.2528, 0.2275, 0.2058, 0.1880, 0.1713,
              0.1538, 0.1384, 0.1275, 0.1143, 0.1041, 0.0905, 0.0856, 0.0819,
              0.0708, 0.0702, 0.0607, 0.0542, 0.0546, 0.0481, 0.0458, 0.0446,
              0.0382, 0.0344, 0.0320, 0.0277, 0.0308, 0.0324]
val_loss = [0.4116, 0.3345, 0.3127, 0.2750, 0.2841, 0.2704, 0.2904, 0.2959,
            0.2832, 0.2751, 0.2889, 0.2967, 0.3208, 0.3129, 0.3385, 0.3628,
            0.3816, 0.4073, 0.4080, 0.4351, 0.4154, 0.4451, 0.4779, 0.5013,
            0.4820, 0.5509, 0.5016, 0.5189, 0.5661, 0.5236]

# Plot Accuracy
plt.figure(figsize=(10, 5))
plt.plot(train_acc, label="Train Accuracy")
plt.plot(val_acc, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Train vs Validation Accuracy")
plt.legend()
plt.grid()
plt.show()

# Plot Loss
plt.figure(figsize=(10, 5))
plt.plot(train_loss, label="Train Loss")
plt.plot(val_loss, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Train vs Validation Loss")
plt.legend()
plt.grid()
plt.show()